// This file is generated by the build script. DO NOT EDIT MANUALLY.
// Environment configuration loaded from .env file
export const ENV_CONFIG = {
  OPENAI_API_KEY: "",
  OPENAI_MODEL: "gpt-4o-mini",
};

// Make environment config available globally for backward compatibility
if (typeof window !== "undefined") {
  window.ENV_CONFIG = ENV_CONFIG;
}

if (typeof globalThis !== "undefined") {
  globalThis.ENV_CONFIG = ENV_CONFIG;
}
